; PlatformIO Project Configuration File
; AmirSwitch - Smart Plug Firmware for ESP32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:load_env.py
lib_deps =
    knolleary/PubSubClient@^2.8
    arduino-libraries/NTPClient@^3.2.1
    bblanchon/ArduinoJson@^6.21.5
